server:
  port: 9091
spring:
  application:
      name: rpc-sample-client
rpc:
  host: 127.0.0.1
  port: 9000
info:
  head: head
  body: body
  ss : dd
management:
  endpoints:
    web:
      exposure:
        #加载所有的端点，默认只加载了info、health
        include: '*'
  endpoint:
    health:
      show-details: always
    #可以关闭指定的端点
    shutdown:
      enabled: false